/**
 * Categorias de cursos e formações acadêmicas disponíveis.
 * Cursos são identificados por UUID (id); use o catálogo abaixo para resolver id <-> nome.
 */
import { v5 as uuidv5 } from "uuid";

const COURSE_NAMESPACE = "a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d";

export const EDUCATION_COURSES = {
    "Alfabetização e Educação Básica": [
        "Alfabetização de Adultos",
        "Educação de Jovens e Adultos (EJA)",
        "Ensino Fundamental Completo",
        "Ensino Médio Completo",
        "Supletivo Ensino Fundamental",
        "Supletivo Ensino Médio"
    ],
    "Cursos Livres e Qualificação Profissional": [
        "Administração de Empresas",
        "Atendimento ao Cliente",
        "Auxiliar Administrativo",
        "Auxiliar de Contabilidade",
        "Auxiliar de Enfermagem",
        "Auxiliar de Farmácia",
        "Auxiliar de Laboratório",
        "Auxiliar de Recursos Humanos",
        "Barista",
        "Bartender",
        "Cabeleireiro",
        "Corte e Costura",
        "Cuidador de Idosos",
        "Cuidador Infantil",
        "Design de Sobrancelhas",
        "Eletricista Residencial",
        "Empreendedorismo",
        "Encanador",
        "English Basic",
        "English Intermediate",
        "English Advanced",
        "Espanhol Básico",
        "Espanhol Intermediário",
        "Espanhol Avançado",
        "Finanças Pessoais",
        "Gestão de Pequenos Negócios",
        "Informática Básica",
        "Informática Intermediária",
        "Informática Avançada",
        "Jardineiro",
        "Libras Básico",
        "Libras Intermediário",
        "Libras Avançado",
        "Maquiagem",
        "Manicure e Pedicure",
        "Mecânica de Automóveis Básica",
        "Microsoft Excel Básico",
        "Microsoft Excel Intermediário",
        "Microsoft Excel Avançado",
        "Microsoft Office",
        "Montador de Móveis",
        "Operador de Caixa",
        "Operador de Empilhadeira",
        "Organização de Eventos",
        "Padeiro e Confeiteiro",
        "Pintor Residencial",
        "Primeiros Socorros",
        "Programação Básica",
        "Recepcionista",
        "Secretariado",
        "Segurança do Trabalho Básico",
        "Técnicas de Vendas",
        "Telemarketing",
        "Web Design Básico",
        "WordPress Básico"
    ],
    "Cursos Técnicos": [
        "Técnico em Administração",
        "Técnico em Agente Comunitário de Saúde",
        "Técnico em Agroecologia",
        "Técnico em Agroindústria",
        "Técnico em Agropecuária",
        "Técnico em Alimentos",
        "Técnico em Análises Clínicas",
        "Técnico em Automação Industrial",
        "Técnico em Biblioteca",
        "Técnico em Cabeamento de Redes",
        "Técnico em Caldeiraria",
        "Técnico em Comércio",
        "Técnico em Comunicação Visual",
        "Técnico em Computação Gráfica",
        "Técnico em Confeitaria",
        "Técnico em Construção Civil",
        "Técnico em Contabilidade",
        "Técnico em Cozinha",
        "Técnico em Design de Interiores",
        "Técnico em Design de Moda",
        "Técnico em Desenvolvimento de Sistemas",
        "Técnico em Edificações",
        "Técnico em Eletricidade",
        "Técnico em Eletroeletrônica",
        "Técnico em Eletromecânica",
        "Técnico em Eletrônica",
        "Técnico em Eletrotécnica",
        "Técnico em Enfermagem",
        "Técnico em Ensaios Físicos e Metalográficos",
        "Técnico em Estética",
        "Técnico em Eventos",
        "Técnico em Farmácia",
        "Técnico em Finanças",
        "Técnico em Florestas",
        "Técnico em Geologia",
        "Técnico em Guia de Turismo",
        "Técnico em Hardware",
        "Técnico em Hemoterapia",
        "Técnico em Hospedagem",
        "Técnico em Hotelaria",
        "Técnico em Informática",
        "Técnico em Informática para Internet",
        "Técnico em Instrumentação Cirúrgica",
        "Técnico em Instrumentação Industrial",
        "Técnico em Logística",
        "Técnico em Mecânica",
        "Técnico em Mecatrônica",
        "Técnico em Meio Ambiente",
        "Técnico em Mineração",
        "Técnico em Nutrição e Dietética",
        "Técnico em Óptica",
        "Técnico em Panificação",
        "Técnico em Petróleo e Gás",
        "Técnico em Podologia",
        "Técnico em Processos Fotográficos",
        "Técnico em Produção de Áudio e Vídeo",
        "Técnico em Produção de Moda",
        "Técnico em Programação de Jogos Digitais",
        "Técnico em Prótese Dentária",
        "Técnico em Química",
        "Técnico em Radiologia",
        "Técnico em Recursos Humanos",
        "Técnico em Redes de Computadores",
        "Técnico em Refrigeração e Climatização",
        "Técnico em Secretariado",
        "Técnico em Segurança do Trabalho",
        "Técnico em Serviços Jurídicos",
        "Técnico em Serviços Públicos",
        "Técnico em Silvicultura",
        "Técnico em Soldagem",
        "Técnico em Telecomunicações",
        "Técnico em Transações Imobiliárias",
        "Técnico em Transportes",
        "Técnico em Turismo",
        "Técnico em Veterinária",
        "Técnico em Zootecnia"
    ],
    "Graduação (Tecnólogo)": [
        "Análise e Desenvolvimento de Sistemas",
        "Automação Industrial",
        "Banco de Dados",
        "Cibersegurança",
        "Comércio Exterior",
        "Construção de Edifícios",
        "Design de Games",
        "Design de Produto",
        "Design Gráfico",
        "Eletrônica Industrial",
        "Embelezamento e Imagem Pessoal",
        "Estética e Cosmética",
        "Eventos",
        "Fabricação Mecânica",
        "Gastronomia",
        "Gestão Ambiental",
        "Gestão Comercial",
        "Gestão da Produção Industrial",
        "Gestão da Qualidade",
        "Gestão da Tecnologia da Informação",
        "Gestão de Cooperativas",
        "Gestão de Recursos Humanos",
        "Gestão de Saúde",
        "Gestão de Segurança Privada",
        "Gestão de Turismo",
        "Gestão Desportiva e de Lazer",
        "Gestão Financeira",
        "Gestão Hospitalar",
        "Gestão Pública",
        "Jogos Digitais",
        "Logística",
        "Manutenção de Aeronaves",
        "Marketing",
        "Mecatrônica Industrial",
        "Processos Gerenciais",
        "Processos Metalúrgicos",
        "Produção Audiovisual",
        "Produção Cervejeira",
        "Produção Fonográfica",
        "Produção Publicitária",
        "Redes de Computadores",
        "Rochas Ornamentais",
        "Secretariado",
        "Segurança da Informação",
        "Segurança no Trabalho",
        "Sistemas Biomédicos",
        "Sistemas de Telecomunicações",
        "Sistemas para Internet",
        "Sistemas para Internet das Coisas",
        "Transporte Terrestre"
    ],
    "Graduação (Bacharelado)": [
        "Administração",
        "Administração de Empresas",
        "Administração Pública",
        "Agroecologia",
        "Agronomia",
        "Arquitetura e Urbanismo",
        "Arquivologia",
        "Artes Cênicas",
        "Artes Visuais",
        "Astronomia",
        "Biblioteconomia",
        "Biologia",
        "Biomedicina",
        "Bioquímica",
        "Biotecnologia",
        "Ciência da Computação",
        "Ciências Aeronáuticas",
        "Ciências Atuariais",
        "Ciências Biológicas",
        "Ciências Contábeis",
        "Ciências da Informação",
        "Ciências da Natureza",
        "Ciências da Religião",
        "Ciências de Alimentos",
        "Ciências do Esporte",
        "Ciências do Solo",
        "Ciências Econômicas",
        "Ciências Humanas",
        "Ciências Militares",
        "Ciências Náuticas",
        "Ciências Políticas",
        "Ciências Sociais",
        "Cinema e Audiovisual",
        "Comunicação Social",
        "Dança",
        "Design",
        "Direito",
        "Economia",
        "Educação Física",
        "Enfermagem",
        "Engenharia Acústica",
        "Engenharia Aeroespacial",
        "Engenharia Aeronáutica",
        "Engenharia Agrícola",
        "Engenharia Agronômica",
        "Engenharia Ambiental",
        "Engenharia Biomédica",
        "Engenharia Bioquímica",
        "Engenharia de Alimentos",
        "Engenharia de Aquicultura",
        "Engenharia de Bioprocessos",
        "Engenharia de Computação",
        "Engenharia de Controle e Automação",
        "Engenharia de Energia",
        "Engenharia de Inovação",
        "Engenharia de Materiais",
        "Engenharia de Minas",
        "Engenharia de Pesca",
        "Engenharia de Petróleo",
        "Engenharia de Produção",
        "Engenharia de Software",
        "Engenharia de Sistemas",
        "Engenharia de Sistemas Eletrônicos",
        "Engenharia de Som",
        "Engenharia de Telecomunicações",
        "Engenharia de Transportes",
        "Engenharia Elétrica",
        "Engenharia Eletrônica",
        "Engenharia Física",
        "Engenharia Florestal",
        "Engenharia Hídrica",
        "Engenharia Industrial",
        "Engenharia Mecânica",
        "Engenharia Mecatrônica",
        "Engenharia Metalúrgica",
        "Engenharia Naval",
        "Engenharia Química",
        "Engenharia Sanitária",
        "Engenharia Têxtil",
        "Estatística",
        "Farmácia",
        "Filosofia",
        "Física",
        "Fisioterapia",
        "Fonoaudiologia",
        "Geografia",
        "Geologia",
        "História",
        "Hotelaria",
        "Jornalismo",
        "Letras",
        "Linguística",
        "Matemática",
        "Medicina",
        "Medicina Veterinária",
        "Meteorologia",
        "Música",
        "Nanotecnologia",
        "Nutrição",
        "Oceanografia",
        "Odontologia",
        "Pedagogia",
        "Psicologia",
        "Publicidade e Propaganda",
        "Química",
        "Rádio, TV e Internet",
        "Relações Internacionais",
        "Relações Públicas",
        "Secretariado Executivo",
        "Serviço Social",
        "Sistemas de Informação",
        "Sociologia",
        "Teatro",
        "Teologia",
        "Terapia Ocupacional",
        "Turismo",
        "Zootecnia"
    ],
    "Graduação (Licenciatura)": [
        "Artes Visuais",
        "Biologia",
        "Ciências Biológicas",
        "Ciências da Natureza",
        "Ciências Humanas",
        "Ciências Sociais",
        "Dança",
        "Educação Artística",
        "Educação Especial",
        "Educação Física",
        "Educação Infantil",
        "Espanhol",
        "Estudos Sociais",
        "Filosofia",
        "Física",
        "Geografia",
        "História",
        "Inglês",
        "Letras",
        "Matemática",
        "Música",
        "Pedagogia",
        "Português",
        "Química"
    ],
    "Pós-Graduação Lato Sensu (Especialização)": [
        "Administração de Empresas",
        "Administração de Sistemas",
        "Administração Educacional",
        "Administração Financeira",
        "Administração Hospitalar",
        "Administração Pública",
        "Agronomia",
        "Arquitetura de Software",
        "Auditoria",
        "Big Data",
        "Bioética",
        "Bioinformática",
        "Biologia Molecular",
        "Biotecnologia",
        "Business Intelligence",
        "Ciência de Dados",
        "Ciência Política",
        "Cinema e Audiovisual",
        "Coach e Mentoring",
        "Comércio Exterior",
        "Comunicação Digital",
        "Comunicação e Marketing",
        "Comunicação Empresarial",
        "Construção Civil",
        "Contabilidade",
        "Contabilidade Gerencial",
        "Contabilidade Internacional",
        "Contabilidade Pública",
        "Contabilidade Tributária",
        "Cooperativismo",
        "Criminologia",
        "Customer Success",
        "Design de Interiores",
        "Design de Moda",
        "Design de Produto",
        "Design Gráfico",
        "Design Instrucional",
        "Design Thinking",
        "Desenvolvimento de Aplicativos",
        "Desenvolvimento de Games",
        "Desenvolvimento de Liderança",
        "Desenvolvimento de Pessoas",
        "Desenvolvimento Sustentável",
        "Direito Administrativo",
        "Direito Ambiental",
        "Direito Civil",
        "Direito Constitucional",
        "Direito do Consumidor",
        "Direito do Trabalho",
        "Direito Empresarial",
        "Direito Internacional",
        "Direito Penal",
        "Direito Processual",
        "Direito Tributário",
        "Docência do Ensino Superior",
        "Economia e Finanças",
        "Educação a Distância",
        "Educação Ambiental",
        "Educação Corporativa",
        "Educação Especial",
        "Educação Física Escolar",
        "Educação Inclusiva",
        "Educação Infantil",
        "Empreendedorismo",
        "Enfermagem do Trabalho",
        "Engenharia de Alimentos",
        "Engenharia de Produção",
        "Engenharia de Segurança do Trabalho",
        "Engenharia de Software",
        "Ensino de Ciências",
        "Ensino de História",
        "Ensino de Matemática",
        "Ensino de Português",
        "Especialização em Anestesiologia",
        "Especialização em Cardiologia",
        "Especialização em Dermatologia",
        "Especialização em Endocrinologia",
        "Especialização em Enfermagem",
        "Especialização em Fisioterapia",
        "Especialização em Gastrenterologia",
        "Especialização em Ginecologia",
        "Especialização em Nutrição",
        "Especialização em Oftalmologia",
        "Especialização em Ortopedia",
        "Especialização em Pediatria",
        "Especialização em Psiquiatria",
        "Especialização em Radiologia",
        "Estética e Cosmética",
        "Eventos",
        "Farmácia Clínica",
        "Fashion Business",
        "Finanças Corporativas",
        "Fisioterapia Esportiva",
        "Fisioterapia Hospitalar",
        "Fisioterapia Neurofuncional",
        "Fisioterapia Traumato-Ortopédica",
        "Fotografia",
        "Gestão da Cadeia de Suprimentos",
        "Gestão da Inovação",
        "Gestão da Manutenção",
        "Gestão da Produção",
        "Gestão da Qualidade de Vida no Trabalho",
        "Gestão da Segurança Privada",
        "Gestão da Tecnologia da Informação",
        "Gestão de Agronegócios",
        "Gestão de Carreiras",
        "Gestão de Compras",
        "Gestão de Condomínios",
        "Gestão de Conflitos",
        "Gestão de Construções",
        "Gestão de Crise",
        "Gestão de E-commerce",
        "Gestão de Energia",
        "Gestão de Equipes",
        "Gestão de Estoques",
        "Gestão de Frota",
        "Gestão de Hospitais",
        "Gestão de Infraestrutura",
        "Gestão de Investimentos",
        "Gestão de Logística",
        "Gestão de Marketing",
        "Gestão de Negócios",
        "Gestão de Pessoas",
        "Gestão de Projetos",
        "Gestão de Qualidade",
        "Gestão de Recursos Humanos",
        "Gestão de Restaurantes",
        "Gestão de Riscos",
        "Gestão de Saúde",
        "Gestão de Serviços",
        "Gestão de Sistemas de Informação",
        "Gestão de Startups",
        "Gestão de Suprimentos",
        "Gestão de Tecnologia",
        "Gestão de Transportes",
        "Gestão de Turismo",
        "Gestão do Varejo",
        "Gestão Educacional",
        "Gestão Empresarial",
        "Gestão Estratégica",
        "Gestão Financeira",
        "Gestão Hospitalar",
        "Gestão Imobiliária",
        "Gestão Industrial",
        "Gestão Pública",
        "Gestão Socioambiental",
        "Governança Corporativa",
        "Hotelaria Hospitalar",
        "Informática em Saúde",
        "Inteligência Artificial",
        "Inteligência de Mercado",
        "Internet das Coisas",
        "Jornalismo Esportivo",
        "Lean Manufacturing",
        "Liderança e Coaching",
        "Linguística Aplicada",
        "Logística Empresarial",
        "Logística Internacional",
        "Logística Reversa",
        "Marketing de Conteúdo",
        "Marketing Digital",
        "Marketing Esportivo",
        "Marketing Internacional",
        "Marketing Político",
        "Marketing de Serviços",
        "Metodologia de Ensino",
        "Mídias Sociais",
        "Negociação Internacional",
        "Neurociências",
        "Nutrição Clínica",
        "Nutrição Esportiva",
        "Orientação Educacional",
        "Orientação Profissional",
        "Perícia Contábil",
        "Perícia Criminal",
        "Planejamento de Carreira",
        "Planejamento Estratégico",
        "Planejamento Tributário",
        "Podologia",
        "Políticas Públicas",
        "Produção Audiovisual",
        "Produção Cultural",
        "Produção Editorial",
        "Produção Fonográfica",
        "Produção Publicitária",
        "Propriedade Intelectual",
        "Psicologia Analítica",
        "Psicologia Clínica",
        "Psicologia do Esporte",
        "Psicologia do Trabalho",
        "Psicologia Educacional",
        "Psicologia Hospitalar",
        "Psicologia Jurídica",
        "Psicologia Organizacional",
        "Psicopedagogia",
        "Publicidade e Criação",
        "Qualidade de Software",
        "Recursos Humanos",
        "Redes de Computadores",
        "Relações Internacionais",
        "Relações Trabalhistas",
        "Responsabilidade Social",
        "Saúde Coletiva",
        "Saúde da Família",
        "Saúde do Idoso",
        "Saúde Mental",
        "Saúde Ocupacional",
        "Saúde Pública",
        "Segurança da Informação",
        "Segurança de Redes",
        "Segurança do Trabalho",
        "Segurança Pública",
        "Serviço Social",
        "Sistemas de Informação",
        "Sistemas Embarcados",
        "Sistemas para Internet",
        "Tecnologia da Informação",
        "Tecnologia de Alimentos",
        "Tecnologia Educacional",
        "Terceiro Setor",
        "Terapia Cognitivo-Comportamental",
        "Terapia Familiar",
        "Tradução",
        "Transporte e Logística",
        "Turismo e Hotelaria",
        "UX Design",
        "Varejo e Distribuição",
        "Vendas e Negociação",
        "Web Analytics"
    ],
    "MBA (Master in Business Administration)": [
        "MBA em Agribusiness",
        "MBA em Business Analytics",
        "MBA em Comércio Exterior",
        "MBA em Controladoria",
        "MBA em Economia e Finanças",
        "MBA em Empreendedorismo",
        "MBA em Gestão de Negócios",
        "MBA em Gestão de Projetos",
        "MBA em Gestão Empresarial",
        "MBA em Gestão Financeira",
        "MBA em Gestão de Pessoas",
        "MBA em Gestão Pública",
        "MBA em Marketing",
        "MBA em Tecnologia da Informação",
        "MBA em Varejo"
    ],
    "Pós-Graduação Stricto Sensu": [
        "Mestrado em Administração",
        "Mestrado em Agronomia",
        "Mestrado em Arquitetura e Urbanismo",
        "Mestrado em Artes",
        "Mestrado em Biologia",
        "Mestrado em Ciência da Computação",
        "Mestrado em Ciências da Saúde",
        "Mestrado em Ciências Sociais",
        "Mestrado em Comunicação",
        "Mestrado em Direito",
        "Mestrado em Economia",
        "Mestrado em Educação",
        "Mestrado em Enfermagem",
        "Mestrado em Engenharia",
        "Mestrado em Filosofia",
        "Mestrado em Física",
        "Mestrado em Geografia",
        "Mestrado em História",
        "Mestrado em Letras",
        "Mestrado em Matemática",
        "Mestrado em Medicina",
        "Mestrado em Nutrição",
        "Mestrado em Odontologia",
        "Mestrado em Psicologia",
        "Mestrado em Química",
        "Mestrado em Serviço Social",
        "Mestrado em Sociologia",
        "Mestrado em Zootecnia",
        "Doutorado em Administração",
        "Doutorado em Agronomia",
        "Doutorado em Arquitetura e Urbanismo",
        "Doutorado em Artes",
        "Doutorado em Biologia",
        "Doutorado em Ciência da Computação",
        "Doutorado em Ciências da Saúde",
        "Doutorado em Ciências Sociais",
        "Doutorado em Comunicação",
        "Doutorado em Direito",
        "Doutorado em Economia",
        "Doutorado em Educação",
        "Doutorado em Enfermagem",
        "Doutorado em Engenharia",
        "Doutorado em Filosofia",
        "Doutorado em Física",
        "Doutorado em Geografia",
        "Doutorado em História",
        "Doutorado em Letras",
        "Doutorado em Matemática",
        "Doutorado em Medicina",
        "Doutorado em Nutrição",
        "Doutorado em Odontologia",
        "Doutorado em Psicologia",
        "Doutorado em Química",
        "Doutorado em Serviço Social",
        "Doutorado em Sociologia",
        "Doutorado em Zootecnia"
    ],
    "Cursos de Extensão e Aperfeiçoamento": [
        "Atualização em Direito Trabalhista",
        "Atualização em Normas Contábeis",
        "Atualização em Tecnologia",
        "Curso de Atualização Profissional",
        "Curso de Extensão Cultural",
        "Curso de Extensão Universitária",
        "Curso de Férias",
        "Workshop de Desenvolvimento Pessoal",
        "Workshop de Inovação",
        "Workshop de Liderança",
        "Workshop de Marketing Digital",
        "Workshop de Oratória",
        "Workshop de Produtividade"
    ],
    "Cursos Online (EAD)": [
        "Administração EAD",
        "Análise e Desenvolvimento de Sistemas EAD",
        "Ciência da Computação EAD",
        "Comércio Exterior EAD",
        "Contabilidade EAD",
        "Direito EAD",
        "Educação Física EAD",
        "Enfermagem EAD",
        "Engenharia de Produção EAD",
        "Engenharia de Software EAD",
        "Gestão de Recursos Humanos EAD",
        "Gestão Financeira EAD",
        "Letras EAD",
        "Logística EAD",
        "Marketing EAD",
        "Pedagogia EAD",
        "Processos Gerenciais EAD",
        "Psicologia EAD",
        "Radiologia EAD",
        "Sistemas de Informação EAD",
        "Tecnologia em Redes de Computadores EAD"
    ],
    "Certificações Profissionais": [
        "AWS Certified Solutions Architect",
        "Certificação PMP (Project Management Professional)",
        "Cisco CCNA",
        "CompTIA A+",
        "CompTIA Security+",
        "Google Ads Certification",
        "Google Analytics Certification",
        "ITIL Foundation",
        "Microsoft Certified: Azure Administrator",
        "Microsoft Certified: Azure Fundamentals",
        "Microsoft Certified: Data Analyst Associate",
        "Microsoft Certified: Power Platform Fundamentals",
        "Microsoft Office Specialist",
        "Oracle Certified Professional",
        "Scrum Master Certified",
        "Six Sigma Green Belt",
        "TOEFL",
        "TOEIC"
    ]
} as const;

export type EducationCategoryKey = keyof typeof EDUCATION_COURSES;

/** Um curso do catálogo com id UUID estável (v5 a partir do nome). */
export interface CourseCatalogEntry {
    id: string;
    name: string;
    categoryKey: EducationCategoryKey;
}

/** Lista plana de todos os cursos com id (UUID). */
const _buildCatalog = (): CourseCatalogEntry[] => {
    const list: CourseCatalogEntry[] = [];
    for (const categoryKey of Object.keys(EDUCATION_COURSES) as EducationCategoryKey[]) {
        const names = EDUCATION_COURSES[categoryKey];
        for (const name of names) {
            list.push({
                id: uuidv5(name, COURSE_NAMESPACE),
                name,
                categoryKey,
            });
        }
    }
    return list;
};

export const COURSES_CATALOG: CourseCatalogEntry[] = _buildCatalog();

/** Mapa id -> curso (para exibir nome a partir do id). */
export const COURSES_BY_ID: Record<string, CourseCatalogEntry> = Object.fromEntries(
    COURSES_CATALOG.map((c) => [c.id, c])
);

/** Mapa nome -> id (para obter id ao selecionar pelo nome). */
export const COURSES_BY_NAME: Record<string, string> = Object.fromEntries(
    COURSES_CATALOG.map((c) => [c.name, c.id])
);

/**
 * Retorna o curso do catálogo pelo id, ou undefined se não existir.
 */
export function getCourseById(id: string): CourseCatalogEntry | undefined {
    return COURSES_BY_ID[id];
}

/**
 * Retorna o id (UUID) do curso pelo nome, ou undefined se não estiver no catálogo.
 */
export function getCourseIdByName(name: string): string | undefined {
    return COURSES_BY_NAME[name];
}

/**
 * Gera um id estável para um curso customizado (fora do catálogo).
 * Usa o mesmo namespace para consistência.
 */
export function getCustomCourseId(customName: string): string {
    return uuidv5(`custom:${customName.trim()}`, COURSE_NAMESPACE);
}

/**
 * Valor armazenado no perfil: id (UUID) do catálogo ou "custom:Nome" para curso personalizado.
 * Retorna o nome para exibição.
 */
export function getCourseDisplayName(entry: string): string {
    if (entry.startsWith("custom:")) {
        return entry.slice(7);
    }
    const course = COURSES_BY_ID[entry];
    return course ? course.name : entry;
}

/**
 * Ao adicionar curso pelo nome: se estiver no catálogo retorna o UUID; senão retorna "custom:Nome".
 */
export function toCourseStorageValue(nameOrId: string): string {
    const trimmed = nameOrId.trim();
    const id = COURSES_BY_NAME[trimmed];
    if (id) return id;
    return `custom:${trimmed}`;
}
