/**
 * Categorias de serviços freelancer disponíveis
 */
// export const FREELANCER_SERVICES = {
//     "Desenvolvimento Web": [
//         "Desenvolvimento Frontend",
//         "Desenvolvimento Backend",
//         "Full Stack",
//         "E-commerce",
//         "Landing Pages",
//         "WordPress",
//     ],
//     "Design": [
//         "Design Gráfico",
//         "UI/UX Design",
//         "Design de Logos",
//         "Design de Interfaces",
//         "Branding",
//         "Ilustração",
//     ],
//     "Marketing Digital": [
//         "SEO",
//         "Google Ads",
//         "Facebook Ads",
//         "Content Marketing",
//         "Social Media",
//         "Email Marketing",
//     ],
//     "Redação": [
//         "Redação de Conteúdo",
//         "Copywriting",
//         "Tradução",
//         "Revisão de Textos",
//         "Ghostwriting",
//     ],
//     "Consultoria": [
//         "Consultoria em TI",
//         "Consultoria em Marketing",
//         "Consultoria em Gestão",
//         "Consultoria Financeira",
//     ],
//     "Outros": [
//         "Edição de Vídeo",
//         "Fotografia",
//         "Transcrição",
//         "Virtual Assistant",
//     ],
// } as const;





export const FREELANCER_SERVICES = {
    "Administração e Consultoria": [
        "Administração de Empresas",
        "Administração de Condomínios",
        "Assessoria Administrativa",
        "Assessoria Contábil",
        "Assessoria Fiscal",
        "Assessoria Jurídica",
        "Auditoria Contábil",
        "Consultoria em Agronegócios",
        "Consultoria Comercial",
        "Consultoria em Compliance",
        "Consultoria em Cooperativismo",
        "Consultoria em Custos",
        "Consultoria Empresarial",
        "Consultoria em Exportação",
        "Consultoria Financeira",
        "Consultoria em Franquias",
        "Consultoria em Gestão",
        "Consultoria em Gestão de Crise",
        "Consultoria em Gestão de Pessoas",
        "Consultoria em Gestão de Processos",
        "Consultoria em Gestão de Projetos",
        "Consultoria em Gestão de Qualidade",
        "Consultoria em Gestão de Riscos",
        "Consultoria em Importação",
        "Consultoria em Inovação",
        "Consultoria em Logística",
        "Consultoria em Marketing",
        "Consultoria em Negócios",
        "Consultoria em Organização Empresarial",
        "Consultoria em Planejamento Estratégico",
        "Consultoria em Processos",
        "Consultoria em Produção",
        "Consultoria em Qualidade",
        "Consultoria em Recursos Humanos",
        "Consultoria em Reestruturação Empresarial",
        "Consultoria em Segurança do Trabalho",
        "Consultoria em Startups",
        "Consultoria em Sustentabilidade",
        "Consultoria em Tecnologia",
        "Consultoria em Terceirização",
        "Consultoria em Varejo",
        "Controladoria",
        "Gestão de Documentos",
        "Gestão de Frota",
        "Gestão de Patrimônio",
        "Gestão de Suprimentos",
        "Gestão Financeira",
        "Gestão Orçamentária",
        "Organização de Arquivos",
        "Organização de Documentos",
        "Planejamento Tributário",
        "Recuperação de Crédito",
        "Revisão de Processos Administrativos"
    ],
    "Arquitetura e Engenharia": [
        "Acompanhamento de Obras",
        "Anteprojeto Arquitetônico",
        "Arquitetura de Interiores",
        "Arquitetura Comercial",
        "Arquitetura Residencial",
        "Arquitetura Sustentável",
        "Cálculo Estrutural",
        "Consultoria em Acústica",
        "Consultoria em Conforto Térmico",
        "Consultoria em Eficiência Energética",
        "Consultoria em Ergonomia",
        "Consultoria em Instalações",
        "Consultoria em Projetos",
        "Consultoria em Segurança Contra Incêndio",
        "Criação de Maquetes Eletrônicas",
        "Desenhos Técnicos",
        "Design de Fachadas",
        "Design de Jardins",
        "Elaboração de APRT (Anotação de Responsabilidade Técnica)",
        "Elaboração de ART (Anotação de Responsabilidade Técnica)",
        "Elaboração de Cronogramas",
        "Elaboração de Estudos de Viabilidade",
        "Elaboração de Laudos Técnicos",
        "Elaboração de Manuais de Uso e Operação",
        "Elaboração de Memoriais Descritivos",
        "Elaboração de Orçamentos",
        "Elaboração de Planilhas de Quantitativos",
        "Elaboração de Projetos Complementares",
        "Elaboração de Projetos Executivos",
        "Engenharia de Avaliações",
        "Engenharia de Custos",
        "Engenharia de Manutenção",
        "Engenharia de Produção",
        "Engenharia de Segurança do Trabalho",
        "Engenharia Legal",
        "Estudo de Insolação",
        "Estudo de Ventilação",
        "Gerenciamento de Obras",
        "Gestão de Contratos",
        "Inspeção Predial",
        "Legislação Urbanística",
        "Levantamento Planialtimétrico",
        "Levantamento Topográfico",
        "Licenciamento Ambiental",
        "Maquete Física",
        "Memorial de Cálculo",
        "Modelagem 3D Arquitetônica",
        "Paisagismo",
        "Perícia de Engenharia",
        "Planejamento Urbano",
        "Projeto de Acessibilidade",
        "Projeto de Áreas Comuns",
        "Projeto de Edificações",
        "Projeto de Eletricidade",
        "Projeto de Estruturas",
        "Projeto de Hidráulica",
        "Projeto de Iluminação",
        "Projeto de Impermeabilização",
        "Projeto de Instalações",
        "Projeto de Interiores",
        "Projeto de Paisagismo",
        "Projeto de Prevenção Contra Incêndio",
        "Projeto de Revestimentos",
        "Projeto de Sanitária",
        "Projeto de Sinalização",
        "Projeto Elétrico",
        "Projeto Executivo",
        "Projeto Hidrossanitário",
        "Projeto Luminotécnico",
        "Projeto Predial",
        "Projeto Residencial",
        "Regularização de Imóveis",
        "Renderização Arquitetônica",
        "Reforma de Projetos",
        "Retrofit",
        "Sondagem do Solo",
        "Supervisão de Obras",
        "Vistoria Técnica"
    ],
    "Beleza e Estética": [
        "Alongamento de Unhas",
        "Aplicação de Extensão de Cílios",
        "Barbearia",
        "Cabeleireiro",
        "Coloração Capilar",
        "Consultoria em Imagem Pessoal",
        "Corte de Cabelo",
        "Corte Masculino",
        "Design de Sobrancelhas",
        "Depilação",
        "Dia da Noiva",
        "Escova Progressiva",
        "Estética Corporal",
        "Estética Facial",
        "Hidratação Capilar",
        "Maquiagem",
        "Maquiagem Artística",
        "Maquiagem para Eventos",
        "Manicure",
        "Massagem",
        "Massagem Relaxante",
        "Massagem Terapêutica",
        "Microagulhamento",
        "Micropigmentação",
        "Pedicure",
        "Penteados",
        "Podologia",
        "Química Capilar",
        "Sobrancelha Design",
        "Terapias Alternativas",
        "Tratamento Capilar",
        "Tratamento para Acne",
        "Visagismo"
    ],
    "Construção Civil e Reformas": [
        "Acabamento em Gesso",
        "Assentamento de Azulejo",
        "Assentamento de Cerâmica",
        "Assentamento de Porcelanato",
        "Carpintaria",
        "Construção de Muros",
        "Construção de Piscinas",
        "Demolição",
        "Drywall",
        "Elétrica Residencial",
        "Encanamento",
        "Encanador",
        "Ferragens",
        "Forro de PVC",
        "Gesseiro",
        "Hidráulica",
        "Impermeabilização",
        "Instalação de Ar Condicionado",
        "Instalação de Forro",
        "Instalação de Pisos",
        "Instalação de Portas e Janelas",
        "Instalação de Sistema de Segurança",
        "Instalação Elétrica",
        "Isolamento Acústico",
        "Isolamento Térmico",
        "Ladrilheiro",
        "Marcenaria",
        "Mestre de Obras",
        "Montagem de Móveis",
        "Montagem de Persianas",
        "Paisagismo",
        "Pintor",
        "Pintura de Fachadas",
        "Pintura de Parede",
        "Pintura de Teto",
        "Pintura Externa",
        "Pintura Interna",
        "Pintura Residencial",
        "Piso Laminado",
        "Piso Vinílico",
        "Portos e Janelas",
        "Reboco",
        "Reforma de Banheiro",
        "Reforma de Cozinha",
        "Reforma de Escritório",
        "Reforma de Fachada",
        "Reforma de Garagem",
        "Reforma de Interiores",
        "Reforma de Sala",
        "Reforma em Geral",
        "Reparos Hidráulicos",
        "Reparos Elétricos",
        "Restauração de Imóveis",
        "Serralheria",
        "Serviços de Alvenaria",
        "Serviços de Limpeza Pós-Obra",
        "Solda",
        "Telhado",
        "Vidraceiro"
    ],
    "Consultoria em TI e Tecnologia": [
        "Análise de Sistemas",
        "Arquitetura de Redes",
        "Arquitetura de Software",
        "Auditoria de Sistemas",
        "Consultoria em Bancos de Dados",
        "Consultoria em Business Intelligence",
        "Consultoria em Cloud Computing",
        "Consultoria em Cibersegurança",
        "Consultoria em E-commerce",
        "Consultoria em Hardware",
        "Consultoria em Infraestrutura de TI",
        "Consultoria em Integração de Sistemas",
        "Consultoria em Internet das Coisas",
        "Consultoria em Intranet",
        "Consultoria em Mobile",
        "Consultoria em Redes",
        "Consultoria em SaaS",
        "Consultoria em Segurança da Informação",
        "Consultoria em Sistemas ERP",
        "Consultoria em Sistemas Legados",
        "Consultoria em Software Livre",
        "Consultoria em Tecnologia",
        "Consultoria em Testes de Software",
        "Consultoria em Transformação Digital",
        "Desenvolvimento de Estratégia Digital",
        "Governança de TI",
        "Implementação de ERP",
        "Implementação de Sistemas",
        "Migração de Dados",
        "Migração para Nuvem",
        "Otimização de Sistemas",
        "Planejamento de TI",
        "Seleção de Software",
        "Suporte Técnico Remoto",
        "Treinamento em TI"
    ],
    "Design e Multimídia": [
        "Animação 2D",
        "Animação 3D",
        "Arte para Redes Sociais",
        "Branding",
        "Criação de Apresentações",
        "Criação de Artes para Impressão",
        "Criação de Banners",
        "Criação de Cartão de Visita",
        "Criação de Catálogos",
        "Criação de Characters",
        "Criação de Convites",
        "Criação de E-books",
        "Criação de Embalagens",
        "Criação de Flyers",
        "Criação de Folders",
        "Criação de Identidade Visual",
        "Criação de Ilustrações",
        "Criação de Infográficos",
        "Criação de Layout",
        "Criação de Logotipo",
        "Criação de Manual de Identidade Visual",
        "Criação de Material Gráfico",
        "Criação de Mockups",
        "Criação de Panfletos",
        "Criação de Posts para Redes Sociais",
        "Criação de Rótulos",
        "Design de Apresentações",
        "Design de Banner",
        "Design de Capa de Livro",
        "Design de Cartaz",
        "Design de Embalagem",
        "Design de Etiquetas",
        "Design de Experiência do Usuário (UX)",
        "Design de Interface do Usuário (UI)",
        "Design de Jogos",
        "Design de Personagens",
        "Design de Produto",
        "Design Editorial",
        "Design Gráfico",
        "Design para Mídias Sociais",
        "Diagramação",
        "Edição de Fotos",
        "Edição de Imagens",
        "Edição de Vídeo",
        "Fotografia de Produto",
        "Ilustração Digital",
        "Ilustração Vetorial",
        "Imagens 3D",
        "Manipulação de Imagens",
        "Manual de Marca",
        "Motion Graphics",
        "Produção Gráfica",
        "Renderização 3D",
        "Retoque Fotográfico",
        "Storyboard",
        "Vetorização",
        "Vídeos Animados",
        "Web Design"
    ],
    "Desenvolvimento de Software e Sites": [
        "Análise de Requisitos",
        "Aplicativos Android",
        "Aplicativos iOS",
        "Automação de Processos",
        "Chatbots",
        "Criação de APIs",
        "Criação de Blogs",
        "Criação de E-commerce",
        "Criação de Landing Pages",
        "Criação de Lojas Virtuais",
        "Criação de Plugins",
        "Criação de Sites Institucionais",
        "Criação de Sistemas Web",
        "Criação de Themes",
        "Desenvolvimento Backend",
        "Desenvolvimento de Aplicativos",
        "Desenvolvimento de Aplicativos Híbridos",
        "Desenvolvimento de Aplicativos Mobile",
        "Desenvolvimento de Extensões de Navegador",
        "Desenvolvimento de Games",
        "Desenvolvimento de Jogos Mobile",
        "Desenvolvimento de Plataformas",
        "Desenvolvimento de Plugins para WordPress",
        "Desenvolvimento de Scripts",
        "Desenvolvimento de Sistemas",
        "Desenvolvimento de Software",
        "Desenvolvimento de Soluções Personalizadas",
        "Desenvolvimento de Websites",
        "Desenvolvimento Frontend",
        "Desenvolvimento Full Stack",
        "Integração de APIs",
        "Integração de Pagamentos",
        "Manutenção de Sites",
        "Migração de Sites",
        "Otimização de Sites",
        "Programação em Java",
        "Programação em JavaScript",
        "Programação em PHP",
        "Programação em Python",
        "Sistemas de Gestão",
        "Web Scraping"
    ],
    "Educação e Ensino": [
        "Acompanhamento Escolar",
        "Aula de Canto",
        "Aula de Dança",
        "Aula de Espanhol",
        "Aula de Física",
        "Aula de Francês",
        "Aula de Geografia",
        "Aula de História",
        "Aula de Inglês",
        "Aula de Italiano",
        "Aula de Libras",
        "Aula de Matemática",
        "Aula de Música",
        "Aula de Piano",
        "Aula de Português",
        "Aula de Química",
        "Aula de Violão",
        "Aula Particular",
        "Aulas de Reforço Escolar",
        "Consultoria Educacional",
        "Criação de Conteúdo Educacional",
        "Criação de Cursos Online",
        "Criação de Material Didático",
        "Desenvolvimento de Conteúdo Pedagógico",
        "Elaboração de Apostilas",
        "Elaboração de Exercícios",
        "Elaboração de Provas",
        "Ensino de Idiomas",
        "Ensino à Distância",
        "Mentoria Acadêmica",
        "Orientação de TCC",
        "Orientação Educacional",
        "Preparação para Concursos",
        "Preparação para Enem",
        "Preparação para Vestibular",
        "Revisão de Trabalhos Acadêmicos",
        "Tradução de Material Acadêmico",
        "Tutoria Online"
    ],
    "Eventos e Cerimonial": [
        "Animação de Eventos",
        "Bartender",
        "Buffet",
        "Cerimonial",
        "Coordenação de Casamento",
        "Coordenação de Eventos",
        "Decoração de Eventos",
        "Decoração de Festas",
        "Decoração de Festas Infantis",
        "Decoração de Mesas",
        "Decoração de Salões",
        "DJ",
        "Fotografia de Casamento",
        "Fotografia de Eventos",
        "Garçom",
        "Locação de Equipamentos",
        "Locução de Eventos",
        "Maquiagem para Eventos",
        "Mestre de Cerimônias",
        "Montagem de Estruturas para Eventos",
        "Organização de Aniversários",
        "Organização de Abertura de Empresa",
        "Organização de Bodas",
        "Organização de Casamentos",
        "Organização de Coffee Break",
        "Organização de Conferências",
        "Organização de Convenções",
        "Organização de Eventos Corporativos",
        "Organização de Eventos Culturais",
        "Organização de Eventos Esportivos",
        "Organização de Eventos Sociais",
        "Organização de Festas",
        "Organização de Formaturas",
        "Organização de Palestras",
        "Organização de Reuniões",
        "Organização de Workshops",
        "Pacotes para Eventos",
        "Palhaço para Festas Infantis",
        "Penteados para Eventos",
        "Planejamento de Eventos",
        "Produção de Eventos",
        "Recepção de Eventos",
        "Segurança para Eventos",
        "Serviço de Bartender",
        "Serviço de Camareira",
        "Sonorização",
        "Transporte para Eventos"
    ],
    "Gastronomia e Alimentação": [
        "Almoxarifado",
        "Bartender",
        "Buffet",
        "Catering",
        "Chef a Domicílio",
        "Confeitaria",
        "Cozinha Árabe",
        "Cozinha Baiana",
        "Cozinha Brasileira",
        "Cozinha Caseira",
        "Cozinha Contemporânea",
        "Cozinha Italiana",
        "Cozinha Japonesa",
        "Cozinha Mineira",
        "Cozinha para Eventos",
        "Cozinheiro",
        "Cozinheiro Pessoal",
        "Cozinheiro para Festas",
        "Degustação",
        "Delivery de Comida",
        "Elaboração de Cardápios",
        "Garçom",
        "Hamburgueria Artesanal",
        "Pizzaiolo",
        "Produção de Alimentos",
        "Serviço de Bartender",
        "Sushiman"
    ],
    "Limpeza e Conservação": [
        "Aspiração",
        "Dedetização",
        "Faxina",
        "Higienização de Ambientes",
        "Impermeabilização de Estofados",
        "Lavagem de Carpetes",
        "Lavagem de Estofados",
        "Lavagem de Persianas",
        "Lavagem de Tapetes",
        "Limpeza de Ar Condicionado",
        "Limpeza de Caixa d'Água",
        "Limpeza de Chão",
        "Limpeza de Condomínios",
        "Limpeza de Escritórios",
        "Limpeza de Estofados",
        "Limpeza de Fachadas",
        "Limpeza de Janelas",
        "Limpeza de Lojas",
        "Limpeza de Piscinas",
        "Limpeza de Pós-Obra",
        "Limpeza de Residências",
        "Limpeza de Vidros",
        "Limpeza Doméstica",
        "Limpeza Industrial",
        "Limpeza Pós-obra",
        "Limpeza Técnica",
        "Limpeza Verde",
        "Lustração de Piso",
        "Passadoria",
        "Serviço de Ajudante",
        "Serviços de Ajudante Geral",
        "Serviços de Zeladoria"
    ],
    "Logística e Transportes": [
        "Aluguel de Caminhão",
        "Aluguel de Veículos",
        "Carga e Descarga",
        "Condutor de Veículos",
        "Despachante Aduaneiro",
        "Despachante Documentalista",
        "Emissão de Notas Fiscais",
        "Entrega de Documentos",
        "Entrega de Encomendas",
        "Entrega de Malotes",
        "Entrega Rápida",
        "Entregador",
        "Gestão de Frota",
        "Gestão de Logística",
        "Locação de Caminhão",
        "Locação de Veículos",
        "Logística de Distribuição",
        "Logística de Eventos",
        "Logística de Transportes",
        "Maloteiro",
        "Motorista de Aplicativo",
        "Motorista de Caminhão",
        "Motorista de Carro Executivo",
        "Motorista de Delivery",
        "Motorista de Ônibus",
        "Motorista Particular",
        "Motorista de Van",
        "Mudanças",
        "Mudanças Residenciais",
        "Operador de Logística",
        "Remoção de Móveis",
        "Serviço de Frete",
        "Transporte de Animais",
        "Transporte de Cargas",
        "Transporte de Documentos",
        "Transporte de Encomendas",
        "Transporte de Mercadorias",
        "Transporte de Mudanças",
        "Transporte de Pessoas",
        "Transporte Escolar",
        "Transporte Executivo",
        "Transporte de Produtos"
    ],
    "Marketing Digital e Vendas": [
        "Análise de Concorrência",
        "Análise de Dados de Marketing",
        "Análise de Mercado",
        "Anúncios Patrocinados",
        "Automation Marketing",
        "Branding",
        "Campanhas de Email Marketing",
        "Campanhas de Marketing Digital",
        "Community Management",
        "Consultoria em Marketing",
        "Copywriting",
        "Criação de Campanhas Publicitárias",
        "Criação de Conteúdo para Blog",
        "Criação de Conteúdo para Redes Sociais",
        "Criação de Funil de Vendas",
        "Criação de Newsletters",
        "Criação de Personas",
        "Criação de Plano de Marketing",
        "Email Marketing",
        "Estratégia de Conteúdo",
        "Estratégia de Mídias Sociais",
        "Facebook Ads",
        "Gestão de Anúncios",
        "Gestão de Campanhas de Tráfego Pago",
        "Gestão de Comunidade",
        "Gestão de Conteúdo",
        "Gestão de Crise em Mídias Sociais",
        "Gestão de Google Ads",
        "Gestão de Instagram",
        "Gestão de LinkedIn",
        "Gestão de Mídias Sociais",
        "Gestão de Tráfego",
        "Gestão de YouTube",
        "Google Ads",
        "Growth Hacking",
        "Inbound Marketing",
        "Instagram Ads",
        "LinkedIn Ads",
        "Marketing de Afiliados",
        "Marketing de Conteúdo",
        "Marketing de Influência",
        "Marketing de Relacionamento",
        "Marketing Digital",
        "Marketing Esportivo",
        "Marketing para Médicos",
        "Marketing para Profissionais Liberais",
        "Marketing Político",
        "Marketing para Restaurantes",
        "Otimização de Conversão (CRO)",
        "Planejamento de Mídia",
        "Produção de Conteúdo",
        "Relatórios de Marketing",
        "SEO (Otimização para Sites de Busca)",
        "Social Media",
        "Tráfego Pago",
        "YouTube Marketing"
    ],
    "Moda e Costura": [
        "Alfaiataria",
        "Ajustes em Roupas",
        "Arrumação de Guarda-roupas",
        "Conserto de Roupas",
        "Consultoria de Moda",
        "Costura",
        "Costura Criativa",
        "Criação de Bolsas",
        "Criação de Roupas",
        "Criação de Uniformes",
        "Customização de Roupas",
        "Design de Moda",
        "Estilismo",
        "Modelagem",
        "Personal Stylist",
        "Reforma de Roupas",
        "Reparo de Roupas",
        "Upcycling de Roupas"
    ],
    "Produção de Conteúdo e Redação": [
        "Blog Posts",
        "Case Studies",
        "Copywriting",
        "Criação de Apostilas",
        "Criação de Artigos",
        "Criação de Conteúdo para Blog",
        "Criação de Conteúdo para E-books",
        "Criação de Conteúdo para Email Marketing",
        "Criação de Conteúdo para Sites",
        "Criação de Descritivos de Produtos",
        "Criação de E-books",
        "Criação de Guias",
        "Criação de Landing Pages",
        "Criação de Manuais",
        "Criação de Newsletters",
        "Criação de Posts para Redes Sociais",
        "Criação de Roteiros",
        "Criação de Scripts para Vídeos",
        "Criação de Textos Publicitários",
        "Criação de Tutoriais",
        "Descrição de Produtos",
        "Edição de Textos",
        "Escrita Criativa",
        "Ghostwriting",
        "Produção de Conteúdo Técnico",
        "Redação Acadêmica",
        "Redação Comercial",
        "Redação de Artigos",
        "Redação de Conteúdo",
        "Redação de Conteúdo para SEO",
        "Redação de Dissertações",
        "Redação de Email Marketing",
        "Redação de Livros",
        "Redação de Monografias",
        "Redação de Posts",
        "Redação de Releases",
        "Redação de Resenhas",
        "Redação de Roteiros",
        "Redação de Textos para Sites",
        "Redação de TCC",
        "Redação Jornalística",
        "Redação para Blog",
        "Redação Publicitária",
        "Reescrita",
        "Revisão de Textos",
        "Revisão Ortográfica",
        "Tradução de Textos"
    ],
    "Saúde e Bem-estar": [
        "Acupuntura",
        "Acompanhante de Idosos",
        "Acompanhante para Consultas Médicas",
        "Aromaterapia",
        "Aulas de Alongamento",
        "Aulas de Dança",
        "Aulas de Pilates",
        "Aulas de Yoga",
        "Coach de Emagrecimento",
        "Consultoria em Nutrição",
        "Cuidador de Idosos",
        "Cuidador de Pessoas com Deficiência",
        "Dietas Personalizadas",
        "Fisioterapia",
        "Fisioterapia Domiciliar",
        "Massagem Relaxante",
        "Massagem Terapêutica",
        "Meditação Guiada",
        "Nutricionista",
        "Personal Trainer",
        "Pilates",
        "Quiropraxia",
        "Reiki",
        "Shiatsu",
        "Terapia Alternativa",
        "Treinamento Personalizado",
        "Yoga"
    ],
    "Serviços Domésticos": [
        "Babá",
        "Cozinhar",
        "Cuidador de Animais",
        "Cuidador de Crianças",
        "Cuidador de Idosos",
        "Cuidador de Plantas",
        "Empregada Doméstica",
        "Jardineiro",
        "Lavagem de Roupas",
        "Limpeza de Casa",
        "Limpeza de Janelas",
        "Limpeza de Piscinas",
        "Organização de Casa",
        "Organização de Guarda-roupas",
        "Organização de Moveis",
        "Organização Residencial",
        "Passadeira",
        "Serviços de Jardinagem",
        "Serviços de Limpeza",
        "Zeladoria"
    ],
    "Serviços Especializados": [
        "Assistência Técnica de Celulares",
        "Assistência Técnica de Computadores",
        "Assistência Técnica de Eletrodomésticos",
        "Calibração de Instrumentos",
        "Chaveiro",
        "Conserto de Celulares",
        "Conserto de Computadores",
        "Conserto de Eletrodomésticos",
        "Conserto de Impressoras",
        "Conserto de Notebooks",
        "Contador",
        "Despachante",
        "Detetive Particular",
        "Engraxate",
        "Instalação de Antenas",
        "Instalação de Câmeras de Segurança",
        "Instalação de Sistemas de Alarme",
        "Manutenção de Ar Condicionado",
        "Manutenção de Computadores",
        "Manutenção de Eletrodomésticos",
        "Manutenção de Impressoras",
        "Manutenção de Notebooks",
        "Perito",
        "Piscineiro",
        "Recuperação de Dados",
        "Segurança Eletrônica",
        "Técnico em Ar Condicionado",
        "Técnico em Celular",
        "Técnico em Eletrônica",
        "Técnico em Informática",
        "Vigilante"
    ],
    "Tradução e Idiomas": [
        "Interpretação Simultânea",
        "Legendagem",
        "Revisão de Traduções",
        "Tradução Comercial",
        "Tradução de Documentos",
        "Tradução de Documentos Acadêmicos",
        "Tradução de Documentos Comerciais",
        "Tradução de Documentos Jurídicos",
        "Tradução de Documentos Médicos",
        "Tradução de Documentos Técnicos",
        "Tradução de Inglês",
        "Tradução de Espanhol",
        "Tradução de Francês",
        "Tradução de Italiano",
        "Tradução de Japonês",
        "Tradução Jurídica",
        "Tradução Juramentada",
        "Tradução Literária",
        "Tradução Médica",
        "Tradução para Legendas",
        "Tradução Técnica",
        "Tradução de Websites"
    ],
    "Vídeo e Fotografia": [
        "Animação 2D",
        "Animação 3D",
        "Cobertura de Eventos",
        "Criação de Animação",
        "Criação de Vídeo Aulas",
        "Criação de Vídeos Animados",
        "Criação de Vídeos Corporativos",
        "Criação de Vídeos de Produtos",
        "Criação de Vídeos Explicativos",
        "Criação de Vídeos Institucionais",
        "Criação de Vídeos para Redes Sociais",
        "Criação de Vídeos Publicitários",
        "Edição de Imagens",
        "Edição de Vídeo",
        "Fotografia Aérea",
        "Fotografia Arquitetônica",
        "Fotografia de Casamento",
        "Fotografia de Eventos",
        "Fotografia de Família",
        "Fotografia de Gastronomia",
        "Fotografia de Moda",
        "Fotografia de Newborn",
        "Fotografia de Produtos",
        "Fotografia de Retrato",
        "Fotografia Esportiva",
        "Fotografia Infantil",
        "Fotografia para Catálogos",
        "Fotografia para E-commerce",
        "Fotografia Publicitária",
        "Making Of",
        "Motion Graphics",
        "Pós-produção de Imagens",
        "Pós-produção de Vídeo",
        "Produção de Vídeo",
        "Retoque Fotográfico",
        "Trilha Sonora",
        "Vídeos Corporativos",
        "Vídeos para Instagram",
        "Vídeos para TikTok",
        "Vídeos para YouTube"
    ]
} as const;
