/**
 * Sugestões de cargo para autocomplete (PT-BR).
 * O usuário pode escolher da lista ou informar texto livre.
 */
export const JOB_TITLE_SUGGESTIONS: string[] = [
    "Analista de Dados",
    "Analista de RH",
    "Analista de Sistemas",
    "Analista Financeiro",
    "Assistente Administrativo",
    "Assistente Comercial",
    "Atendente",
    "Auxiliar Administrativo",
    "Auxiliar de Escritório",
    "Auxiliar de Logística",
    "Caixa",
    "Consultor Comercial",
    "Coordenador de Equipe",
    "Coordenador de Projetos",
    "Desenvolvedor Backend",
    "Desenvolvedor Frontend",
    "Desenvolvedor Full Stack",
    "Designer Gráfico",
    "Designer UX/UI",
    "Diretor Comercial",
    "Eletricista",
    "Encarregado de Produção",
    "Enfermeiro",
    "Engenheiro Civil",
    "Engenheiro de Produção",
    "Engenheiro de Software",
    "Estagiário",
    "Gerente Comercial",
    "Gerente de Loja",
    "Gerente de Operações",
    "Gerente de Projetos",
    "Mecânico",
    "Motorista",
    "Operador de Caixa",
    "Operador de Máquinas",
    "Recepcionista",
    "Representante Comercial",
    "Supervisor de Vendas",
    "Técnico de Informática",
    "Técnico de Manutenção",
    "Técnico em Enfermagem",
    "Vendedor",
    "Vendedor Interno",
    "Auxiliar de Cozinha",
    "Cozinheiro",
    "Garçom",
    "Promotor de Vendas",
    "Segurança",
    "Zelador",
];
