/**
 * Categorias de habilidades técnicas disponíveis para seleção no perfil
 */
// export const SKILLS_CATEGORIES = {
//     "Linguagens de Programação": [
//         "JavaScript",
//         "TypeScript",
//         "Python",
//         "Java",
//         "C#",
//         "C++",
//         "PHP",
//         "Ruby",
//         "Go",
//         "Rust",
//         "Swift",
//         "Kotlin",
//         "Dart",
//     ],
//     "Frameworks Frontend": [
//         "React",
//         "Vue.js",
//         "Angular",
//         "Next.js",
//         "Svelte",
//         "Nuxt.js",
//         "Remix",
//     ],
//     "Frameworks Backend": [
//         "Express.js",
//         "NestJS",
//         "Django",
//         "Flask",
//         "Spring Boot",
//         "Laravel",
//         "Ruby on Rails",
//         "ASP.NET",
//     ],
//     "Bancos de Dados": [
//         "PostgreSQL",
//         "MySQL",
//         "MongoDB",
//         "Redis",
//         "SQLite",
//         "Oracle",
//         "SQL Server",
//         "Firebase",
//         "Supabase",
//     ],
//     "Cloud & DevOps": [
//         "AWS",
//         "Azure",
//         "Google Cloud",
//         "Docker",
//         "Kubernetes",
//         "CI/CD",
//         "Terraform",
//         "Ansible",
//     ],
//     "Ferramentas de Design": [
//         "Figma",
//         "Adobe XD",
//         "Sketch",
//         "Photoshop",
//         "Illustrator",
//         "InDesign",
//     ],
//     "Testes": [
//         "Jest",
//         "Cypress",
//         "Selenium",
//         "Unit Testing",
//         "Integration Testing",
//         "E2E Testing",
//     ],
// } as const;








export const SKILLS_CATEGORIES = {
    "Administração e Gestão": [
        "Administração de Empresas",
        "Administração Financeira",
        "Administração de Materiais",
        "Administração de Pessoal",
        "Administração de Produção",
        "Administração de Vendas",
        "Análise de Custos",
        "Análise de Processos",
        "Assessoria Administrativa",
        "Atendimento ao Público",
        "Atendimento Telefônico",
        "Auditoria Administrativa",
        "Contabilidade Básica",
        "Controle de Estoque",
        "Controle de Qualidade",
        "Gestão de Documentos",
        "Gestão de Equipes",
        "Gestão de Frota",
        "Gestão de Pessoas",
        "Gestão de Projetos",
        "Gestão de Recursos Humanos",
        "Gestão de Serviços",
        "Gestão de Suprimentos",
        "Logística Administrativa",
        "Planejamento Estratégico",
        "Recepção",
        "Secretariado",
        "Supervisão Administrativa"
    ],
    "Agronegócio e Meio Ambiente": [
        "Agricultura Familiar",
        "Agricultura Orgânica",
        "Agrimensura",
        "Agroecologia",
        "Agroindústria",
        "Agronomia",
        "Aquicultura",
        "Avicultura",
        "Bovinocultura",
        "Cafeicultura",
        "Caprinocultura",
        "Cultivo de Grãos",
        "Cultivo de Hortaliças",
        "Cultivo de Plantas Ornamentais",
        "Desenvolvimento Rural",
        "Educação Ambiental",
        "Engenharia Agronômica",
        "Extensão Rural",
        "Fitotecnia",
        "Floricultura",
        "Fruticultura",
        "Gestão Ambiental",
        "Gestão de Resíduos",
        "Hidroponia",
        "Irrigação",
        "Manejo de Pragas",
        "Manejo Florestal",
        "Meliponicultura",
        "Paisagismo",
        "Pecuária Leiteira",
        "Pecuária de Corte",
        "Permacultura",
        "Piscicultura",
        "Recuperação de Áreas Degradadas",
        "Saneamento Ambiental",
        "Silvicultura",
        "Suinocultura",
        "Técnico Agrícola",
        "Técnico Ambiental",
        "Tratamento de Efluentes",
        "Zootecnia"
    ],
    "Artes e Cultura": [
        "Artesanato",
        "Artes Cênicas",
        "Artes Gráficas",
        "Artes Plásticas",
        "Artes Visuais",
        "Audiovisual",
        "Canto",
        "Cerâmica",
        "Cenografia",
        "Cinema",
        "Circo",
        "Composição Musical",
        "Conservação de Obras de Arte",
        "Coral",
        "Costura Criativa",
        "Dança",
        "Decoração de Ambientes",
        "Design de Arte",
        "Design de Moda",
        "Direção de Arte",
        "Edição de Áudio",
        "Edição de Vídeo",
        "Escultura",
        "Fotografia",
        "Grafite",
        "História da Arte",
        "Ilustração",
        "Jardinagem Artística",
        "Maquiagem Artística",
        "Música",
        "Música Instrumental",
        "Pintura",
        "Produção Artística",
        "Produção Cultural",
        "Produção Musical",
        "Roteiro",
        "Teatro",
        "Técnica Vocal",
        "Violão"
    ],
    "Atendimento e Serviços ao Cliente": [
        "Atendimento ao Cliente",
        "Atendimento ao Fornecedor",
        "Atendimento Comercial",
        "Atendimento de Pós-Venda",
        "Atendimento Farmacêutico",
        "Atendimento Hospitalar",
        "Atendimento Médico",
        "Atendimento Odontológico",
        "Atendimento Pré-Venda",
        "Atendimento Receptivo",
        "Atendimento Telefônico",
        "Atendimento Via Chat",
        "Atendimento Via E-mail",
        "Atendimento Via WhatsApp",
        "Balconista",
        "Caixa",
        "Call Center",
        "Captação de Clientes",
        "Central de Atendimento",
        "Concierge",
        "Consultoria ao Cliente",
        "Fidelização de Clientes",
        "Gestão de Atendimento",
        "Gestão de Relacionamento com Cliente",
        "Operador de Telemarketing",
        "Ouvidoria",
        "Recepção",
        "Relacionamento com Cliente",
        "Resolução de Problemas",
        "Retenção de Clientes",
        "SAC",
        "Secretariado",
        "Suporte ao Cliente",
        "Suporte Técnico",
        "Técnicas de Atendimento",
        "Teleatendimento",
        "Telemarketing Ativo",
        "Telemarketing Receptivo",
        "Vendas por Telefone"
    ],
    "Bancos de Dados": [
        "Apache Cassandra",
        "DynamoDB",
        "Elasticsearch",
        "Firebase",
        "MariaDB",
        "Microsoft SQL Server",
        "MongoDB",
        "MySQL",
        "Oracle Database",
        "PostgreSQL",
        "Redis",
        "SQLite",
        "Supabase",
        "Administração de Bancos de Dados",
        "Análise de Dados",
        "Backup e Recuperação",
        "Consultas SQL",
        "Data Warehouse",
        "ETL",
        "Modelagem de Dados",
        "Otimização de Consultas",
        "Performance Tuning",
        "Replicação de Dados",
        "Segurança de Dados"
    ],
    "Beleza e Estética": [
        "Alongamento de Unhas",
        "Barbeiro",
        "Cabeleireiro",
        "Cílios",
        "Corte Masculino",
        "Corte Feminino",
        "Depilação",
        "Design de Sobrancelhas",
        "Drenagem Linfática",
        "Esteticista",
        "Estética Corporal",
        "Estética Facial",
        "Maquiagem",
        "Manicure",
        "Massagem",
        "Massoterapia",
        "Micropigmentação",
        "Pedicure",
        "Penteados",
        "Podologia",
        "Química Capilar",
        "Tintura de Cabelo",
        "Tratamentos Capilares",
        "Tratamentos Corporais",
        "Tratamentos Faciais",
        "Visagismo"
    ],
    "Cloud & DevOps": [
        "Amazon Web Services",
        "Ansible",
        "Azure",
        "CI/CD",
        "Cloud Computing",
        "Cloud Storage",
        "Containerização",
        "Docker",
        "Google Cloud Platform",
        "Infraestrutura como Código",
        "Kubernetes",
        "Monitoramento de Aplicações",
        "Orquestração de Containers",
        "SaaS",
        "Serverless",
        "Terraform",
        "Virtualização",
        "Administração de Sistemas em Nuvem",
        "Automação de Deploy",
        "Configuração de Ambientes",
        "Contêineres",
        "DevSecOps",
        "Escalabilidade",
        "Gestão de Configuração",
        "Integração Contínua",
        "Logs e Monitoramento",
        "Microserviços",
        "Pipeline de Deploy",
        "Segurança em Cloud"
    ],
    "Comércio e Varejo": [
        "Atendimento ao Cliente",
        "Atendimento no Balcão",
        "Atendimento por Telefone",
        "Balconista",
        "Caixa",
        "Controle de Estoque",
        "Demonstrador de Produtos",
        "Departamento de Compras",
        "Departamento de Vendas",
        "Estoquista",
        "Gerente de Loja",
        "Merchandising",
        "Operador de Caixa",
        "Organização de Vitrines",
        "Promotor de Vendas",
        "Repositor de Mercadorias",
        "Supervisor de Vendas",
        "Técnicas de Vendas",
        "Vendas a Consumidor Final",
        "Vendas Atacado",
        "Vendas Diretas",
        "Vendas por Catálogo",
        "Vendas por Telemarketing",
        "Vendas por WhatsApp",
        "Vendas Varejo"
    ],
    "Construção Civil": [
        "Ajudante de Obra",
        "Alvenaria",
        "Armador",
        "Assentamento de Pisos",
        "Assentamento de Revestimentos",
        "Carpintaria",
        "Concretagem",
        "Construção de Edifícios",
        "Construção de Muros",
        "Demolição",
        "Drywall",
        "Elétrica Predial",
        "Encanador",
        "Encanamento Hidráulico",
        "Ferragens",
        "Gesseiro",
        "Gestão de Obras",
        "Hidráulica",
        "Instalações Elétricas",
        "Instalações Hidrossanitárias",
        "Isolamento Acústico",
        "Isolamento Térmico",
        "Ladrilheiro",
        "Marceneiro",
        "Mestre de Obras",
        "Montador de Estruturas",
        "Pedreiro",
        "Pintor",
        "Pintura de Obras",
        "Pintura Industrial",
        "Pintura Residencial",
        "Piso Laminado",
        "Piso Porcelanato",
        "Piso Vinílico",
        "Reboco",
        "Reformas",
        "Serralheria",
        "Servente de Obra",
        "Telhados",
        "Vidraceiro"
    ],
    "Design e Multimídia": [
        "Adobe After Effects",
        "Adobe Illustrator",
        "Adobe InDesign",
        "Adobe Photoshop",
        "Adobe Premiere",
        "Animações 2D",
        "Animações 3D",
        "Artes Gráficas",
        "Audiodescrição",
        "Blender",
        "Branding",
        "Canva",
        "CorelDRAW",
        "Criação de Logotipos",
        "Design de Apresentações",
        "Design de Banner",
        "Design de Cartão de Visita",
        "Design de Embalagens",
        "Design de Folhetos",
        "Design de Identidade Visual",
        "Design de Interface",
        "Design de Layout",
        "Design de Material Gráfico",
        "Design de Mídias Sociais",
        "Design de Panfletos",
        "Design de Personagens",
        "Design de Posts",
        "Design de Sites",
        "Design Gráfico",
        "Diagramação",
        "Edição de Áudio",
        "Edição de Fotos",
        "Edição de Vídeo",
        "Figma",
        "GIMP",
        "Ilustração Digital",
        "Infográficos",
        "Inkscape",
        "Motion Graphics",
        "Produção Gráfica",
        "Sketch",
        "UI Design",
        "UX Design",
        "Vetorização",
        "Web Design"
    ],
    "Desenvolvimento Backend": [
        "API Gateway",
        "APIs REST",
        "APIs GraphQL",
        "ASP.NET",
        "Autenticação e Autorização",
        "Caching",
        "Desenvolvimento de APIs",
        "Django",
        "Express.js",
        "FastAPI",
        "Flask",
        "Java",
        "Laravel",
        "Microsserviços",
        "NestJS",
        "Node.js",
        "PHP",
        "Python",
        "Ruby on Rails",
        "Scala",
        "Segurança de APIs",
        "Spring Boot",
        "Websockets",
        "Arquitetura de Software",
        "Backend as a Service",
        "Desempenho de Aplicações",
        "Documentação de APIs",
        "Gateway de Pagamento",
        "Integração de Sistemas",
        "Message Queues",
        "Otimização de Código",
        "Padrões de Projeto",
        "Scalability"
    ],
    "Desenvolvimento Frontend": [
        "Angular",
        "Bootstrap",
        "CSS",
        "Chakra UI",
        "HTML",
        "JavaScript",
        "jQuery",
        "Material-UI",
        "Next.js",
        "React",
        "Redux",
        "Remix",
        "Responsive Web Design",
        "SASS/SCSS",
        "Styled Components",
        "Svelte",
        "Tailwind CSS",
        "TypeScript",
        "Vue.js",
        "Web Components",
        "Web Performance",
        "Web Accessibility",
        "Webpack",
        "Vite",
        "AngularJS",
        "Ember.js",
        "Acessibilidade Web",
        "Animações CSS",
        "Cross-browser Compatibility",
        "Design System",
        "Frameworks CSS",
        "JavaScript Moderno",
        "PWA",
        "SEO Frontend",
        "Server Side Rendering",
        "Single Page Applications"
    ],
    "Desenvolvimento Mobile": [
        "Android Development",
        "Dart",
        "Flutter",
        "iOS Development",
        "Kotlin",
        "React Native",
        "Swift",
        "Xamarin",
        "APIs Mobile",
        "App Store",
        "Desenvolvimento Híbrido",
        "Desenvolvimento Nativo",
        "Firebase para Mobile",
        "Google Play Store",
        "Interface para Mobile",
        "Mobile First",
        "Notificações Push",
        "Otimização para Mobile",
        "PWA",
        "Testes em Dispositivos Móveis",
        "UI/UX para Mobile"
    ],
    "Educação e Ensino": [
        "Administração Escolar",
        "Apoio Pedagógico",
        "Auxiliar de Classe",
        "Auxiliar de Creche",
        "Auxiliar de Educação Infantil",
        "Coordenação Pedagógica",
        "Docência em Ensino Fundamental",
        "Docência em Ensino Médio",
        "Docência em Ensino Superior",
        "Educação de Jovens e Adultos",
        "Educação Especial",
        "Educação Infantil",
        "Educação Inclusiva",
        "Ensino à Distância",
        "Ensino de Artes",
        "Ensino de Ciências",
        "Ensino de Educação Física",
        "Ensino de Espanhol",
        "Ensino de Filosofia",
        "Ensino de Física",
        "Ensino de Geografia",
        "Ensino de História",
        "Ensino de Inglês",
        "Ensino de Literatura",
        "Ensino de Matemática",
        "Ensino de Música",
        "Ensino de Português",
        "Ensino de Química",
        "Ensino de Sociologia",
        "Ensino Profissionalizante",
        "Ensino Técnico",
        "Gestão Educacional",
        "Orientação Educacional",
        "Pedagogia",
        "Preparação para Vestibular",
        "Professor Particular",
        "Supervisão Educacional"
    ],
    "Engenharias": [
        "Engenharia Aeronáutica",
        "Engenharia Agronômica",
        "Engenharia Ambiental",
        "Engenharia Biomédica",
        "Engenharia Cartográfica",
        "Engenharia Civil",
        "Engenharia da Computação",
        "Engenharia de Alimentos",
        "Engenharia de Controle e Automação",
        "Engenharia de Materiais",
        "Engenharia de Minas",
        "Engenharia de Produção",
        "Engenharia de Software",
        "Engenharia Elétrica",
        "Engenharia Eletrônica",
        "Engenharia Florestal",
        "Engenharia Mecânica",
        "Engenharia Mecatrônica",
        "Engenharia Naval",
        "Engenharia Química",
        "Engenharia Sanitária",
        "Engenharia de Segurança do Trabalho",
        "Engenharia Têxtil",
        "Engenharia de Transportes"
    ],
    "Finanças e Contabilidade": [
        "Análise de Balanço",
        "Análise de Crédito",
        "Análise de Custos",
        "Análise de Investimentos",
        "Análise Financeira",
        "Auditoria Contábil",
        "Auditoria Fiscal",
        "Auditoria Interna",
        "BPO Financeiro",
        "Contabilidade Comercial",
        "Contabilidade de Custos",
        "Contabilidade Fiscal",
        "Contabilidade Gerencial",
        "Contabilidade Internacional",
        "Contabilidade Pública",
        "Contabilidade Rural",
        "Contabilidade Societária",
        "Contabilidade Tributária",
        "Contas a Pagar",
        "Contas a Receber",
        "Controle Financeiro",
        "Crédito e Cobrança",
        "Demonstrações Financeiras",
        "Departamento Fiscal",
        "Escrita Fiscal",
        "Faturamento",
        "Gestão de Fluxo de Caixa",
        "Gestão Financeira",
        "Planejamento Tributário",
        "Tesouraria"
    ],
    "Gastronomia e Alimentação": [
        "Ajudante de Cozinha",
        "Auxiliar de Cozinha",
        "Churrasqueiro",
        "Copeiro",
        "Cozinha Árabe",
        "Cozinha Baiana",
        "Cozinha Brasileira",
        "Cozinha Contemporânea",
        "Cozinha Francesa",
        "Cozinha Italiana",
        "Cozinha Japonesa",
        "Cozinha Mineira",
        "Cozinha Nordestina",
        "Cozinha Portuguesa",
        "Cozinheiro",
        "Confeitaria",
        "Confeiteiro",
        "Decorador de Bolos",
        "Garçom",
        "Gestão de Restaurantes",
        "Maitre",
        "Padeiro",
        "Pizzaiolo",
        "Preparação de Bebidas",
        "Saladeiro",
        "Sushiman"
    ],
    "Indústria e Manufatura": [
        "Assistente de Produção",
        "Caldeireiro",
        "Calibração de Instrumentos",
        "Controle de Qualidade",
        "Eletricista Industrial",
        "Encarregado de Produção",
        "Engenharia de Produção",
        "Fabricação de Produtos",
        "Fresador",
        "Funileiro Industrial",
        "Gestão da Produção",
        "Inspetor de Qualidade",
        "Instalações Industriais",
        "Linha de Produção",
        "Manutenção Industrial",
        "Mecânica Industrial",
        "Montador Industrial",
        "Operador de Máquinas",
        "Operador de Produção",
        "Pintura Industrial",
        "Processos Industriais",
        "Produção de Automóveis",
        "Produção de Componentes",
        "Produção de Eletrônicos",
        "Produção de Embalagens",
        "Produção de Metais",
        "Produção de Plásticos",
        "Produção de Produtos Alimentícios",
        "Produção de Produtos Farmacêuticos",
        "Produção de Produtos Químicos",
        "Produção de Tecidos",
        "Produção Têxtil",
        "Qualidade Industrial",
        "Segurança Industrial",
        "Soldador",
        "Supervisor de Produção",
        "Torneiro Mecânico",
        "Usinagem"
    ],
    "Liderança e Gestão de Pessoas": [
        "Avaliação de Desempenho",
        "Capacitação de Equipes",
        "Coaching",
        "Comunicação Eficaz",
        "Desenvolvimento de Equipes",
        "Desenvolvimento de Liderança",
        "Feedback",
        "Gestão de Conflitos",
        "Gestão de Desempenho",
        "Gestão de Equipes",
        "Gestão de Mudanças",
        "Gestão de Pessoas",
        "Gestão de Talentos",
        "Liderança",
        "Liderança de Equipes",
        "Liderança Situacional",
        "Mentoria",
        "Motivação de Equipes",
        "Recrutamento e Seleção",
        "Resolução de Conflitos",
        "Supervisão de Equipes",
        "Team Building",
        "Treinamento de Equipes"
    ],
    "Linguagens de Programação": [
        "C",
        "C++",
        "C#",
        "Dart",
        "Go",
        "Java",
        "JavaScript",
        "Kotlin",
        "PHP",
        "Python",
        "R",
        "Ruby",
        "Rust",
        "Scala",
        "Swift",
        "TypeScript",
        "Assembly",
        "Bash/Shell",
        "Clojure",
        "Elixir",
        "F#",
        "Haskell",
        "Julia",
        "Lua",
        "MATLAB",
        "Perl",
        "PowerShell",
        "SQL",
        "Visual Basic"
    ],
    "Logística e Transportes": [
        "Almoxarife",
        "Armazenagem",
        "Carga e Descarga",
        "Conferente de Carga",
        "Controle de Estoque",
        "Despachante Aduaneiro",
        "Distribuição",
        "Emissão de Notas Fiscais",
        "Empilhadeira",
        "Estoquista",
        "Expedição",
        "Frota",
        "Gestão de Armazém",
        "Gestão de Cadeia de Suprimentos",
        "Gestão de Estoques",
        "Gestão de Frotas",
        "Gestão de Logística",
        "Gestão de Transportes",
        "Logística de Distribuição",
        "Logística de Produção",
        "Logística de Suprimentos",
        "Logística Internacional",
        "Logística Reversa",
        "Motorista de Caminhão",
        "Motorista de Carreta",
        "Motorista de Ônibus",
        "Motorista de Vans",
        "Operador de Logística",
        "Operador de Máquinas",
        "Operador de Transporte",
        "Recebimento de Mercadorias",
        "Roteirização",
        "Supply Chain Management",
        "Transporte de Cargas",
        "Transporte de Passageiros",
        "Transporte Rodoviário",
        "Transporte Urbano"
    ],
    "Marketing e Vendas": [
        "Analytics",
        "Atendimento Comercial",
        "Branding",
        "Business Intelligence",
        "Captação de Clientes",
        "Comunicação Digital",
        "Copywriting",
        "CRM",
        "Design de Campanhas",
        "E-mail Marketing",
        "Funil de Vendas",
        "Gestão de Campanhas",
        "Gestão de Conteúdo",
        "Gestão de Mídias Sociais",
        "Gestão de Produto",
        "Gestão de Vendas",
        "Google Ads",
        "Inbound Marketing",
        "Lead Generation",
        "Marketing de Afiliados",
        "Marketing de Conteúdo",
        "Marketing de Influência",
        "Marketing de Relacionamento",
        "Marketing Digital",
        "Marketing Direto",
        "Marketing Estratégico",
        "Marketing Político",
        "Marketing Pós-venda",
        "Marketing Promocional",
        "Marketing Viral",
        "Mídias Sociais",
        "Negociação",
        "Outbound Marketing",
        "Pesquisa de Mercado",
        "Planejamento de Mídia",
        "Publicidade",
        "SEO",
        "Social Media",
        "Telemarketing",
        "Trade Marketing",
        "Vendas Consultivas",
        "Vendas Corporativas",
        "Vendas Diretas",
        "Vendas Online",
        "Vendas por Telefone"
    ],
    "Metalurgia e Siderurgia": [
        "Ajustador Mecânico",
        "Caldeireiro",
        "Corte a Plasma",
        "Corte a Laser",
        "Dobrador de Tubos",
        "Eletricista de Manutenção",
        "Encanador Industrial",
        "Ferramenteiro",
        "Fresador",
        "Fundição",
        "Funileiro",
        "Instalador de Estruturas Metálicas",
        "Manutenção de Equipamentos",
        "Mecânico de Manutenção",
        "Metalúrgico",
        "Montador de Estruturas Metálicas",
        "Operador de CNC",
        "Operador de Máquinas",
        "Pintura Industrial",
        "Serralheiro",
        "Soldador",
        "Solda MIG/MAG",
        "Solda TIG",
        "Solda Eletrodo Revestido",
        "Torneiro Mecânico",
        "Trefilação",
        "Usinagem"
    ],
    "Recursos Humanos": [
        "Administração de Pessoal",
        "Admissão e Demissão",
        "Análise de Cargos e Salários",
        "Avaliação de Desempenho",
        "Benefícios",
        "Cálculo de Folha de Pagamento",
        "Capacitação",
        "Carreira e Sucessão",
        "Clima Organizacional",
        "Coaching",
        "Comunicação Interna",
        "Consultoria em RH",
        "Desenvolvimento Organizacional",
        "Desenvolvimento de Pessoas",
        "Endomarketing",
        "Engajamento",
        "Folha de Pagamento",
        "Gestão de Benefícios",
        "Gestão de Cargos e Salários",
        "Gestão de Pessoas",
        "Gestão de Talentos",
        "Legislação Trabalhista",
        "Mentoria",
        "Onboarding",
        "Pesquisa Salarial",
        "Planejamento de Carreira",
        "Recrutamento",
        "Relações Trabalhistas",
        "Remuneração",
        "Seleção",
        "Treinamento",
        "Welfare"
    ],
    "Saúde e Bem-estar": [
        "Acupuntura",
        "Assistente de Enfermagem",
        "Assistente de Farmácia",
        "Auxiliar de Consultório",
        "Auxiliar de Enfermagem",
        "Auxiliar de Farmácia",
        "Auxiliar de Laboratório",
        "Auxiliar de Saúde Bucal",
        "Cuidador de Idosos",
        "Enfermagem",
        "Esteticista",
        "Farmácia",
        "Fisioterapia",
        "Massoterapia",
        "Nutrição",
        "Odontologia",
        "Psicologia",
        "Radiologia",
        "Recepcionista de Consultório",
        "Técnico de Enfermagem",
        "Técnico de Farmácia",
        "Técnico de Laboratório",
        "Técnico de Radiologia",
        "Terapia Ocupacional",
        "Vigilante Sanitário"
    ],
    "Segurança e Vigilância": [
        "Escolta Armada",
        "Guarda Patrimonial",
        "Portaria",
        "Segurança de Eventos",
        "Segurança Eletrônica",
        "Segurança Patrimonial",
        "Segurança Pessoal",
        "Segurança Privada",
        "Segurança Pública",
        "Vigilância",
        "Vigilante",
        "Controle de Acesso",
        "Monitoramento por Câmeras",
        "Patrulhamento",
        "Prevenção de Perdas",
        "Ronda",
        "Segurança Corporativa",
        "Sistema de Alarme"
    ],
    "Serviços Domésticos e Manutenção": [
        "Armador de Ferragens",
        "Assistente de Serviços Gerais",
        "Auxiliar de Limpeza",
        "Carpinteiro",
        "Cuidador de Animais",
        "Cuidador de Idosos",
        "Cuidador de Pessoas com Deficiência",
        "Doméstica",
        "Eletricista Residencial",
        "Encanador",
        "Faxineiro",
        "Jardineiro",
        "Lavadeira",
        "Limpador de Vidros",
        "Manutenção de Ar Condicionado",
        "Manutenção de Computadores",
        "Manutenção de Eletrodomésticos",
        "Manutenção de Piscinas",
        "Marceneiro",
        "Montador de Móveis",
        "Passadeira",
        "Pintor",
        "Reparador de Celulares",
        "Serviços Gerais",
        "Técnico em Manutenção",
        "Vidraceiro",
        "Zelador"
    ],
    "Tecnologia da Informação": [
        "Administração de Redes",
        "Administração de Sistemas",
        "Arquitetura de Redes",
        "Assistência Técnica de Informática",
        "Cabeamento Estruturado",
        "Computação em Nuvem",
        "Cibersegurança",
        "Consultoria em TI",
        "Data Center",
        "Desenvolvimento de Software",
        "Firewalls",
        "Gestão de TI",
        "Governança de TI",
        "Help Desk",
        "Infraestrutura de TI",
        "Manutenção de Computadores",
        "Redes de Computadores",
        "Segurança da Informação",
        "Servidores",
        "Service Desk",
        "Suporte Técnico",
        "Telecomunicações",
        "Virtualização",
        "Administração de Servidores",
        "Análise de Sistemas",
        "Backup e Recuperação",
        "Certificações de TI",
        "Cloud Computing",
        "Documentação Técnica",
        "Monitoramento de Sistemas",
        "Otimização de Sistemas",
        "Projetos de TI",
        "Sistemas Operacionais",
        "Soluções de TI",
        "Técnico em Informática"
    ],
    "Testes e Qualidade de Software": [
        "Automação de Testes",
        "Cypress",
        "Jest",
        "JUnit",
        "Mocha",
        "Pytest",
        "Selenium",
        "TestNG",
        "Testes de Aceitação",
        "Testes de Acessibilidade",
        "Testes de API",
        "Testes de Carga",
        "Testes de Desempenho",
        "Testes de Integração",
        "Testes de Interface",
        "Testes de Regressão",
        "Testes de Segurança",
        "Testes de Sistema",
        "Testes de Usabilidade",
        "Testes de Unidade",
        "Testes de Validação",
        "Testes de Verificação",
        "Testes E2E",
        "Testes Exploratórios",
        "Testes Funcionais",
        "Testes Manuais",
        "Testes Mobile",
        "Testes Web",
        "BDD",
        "Bug Tracking",
        "Ciclo de Vida de Testes",
        "Cobertura de Testes",
        "Controle de Qualidade",
        "Documentação de Testes",
        "Ferramentas de Teste",
        "Gestão de Defeitos",
        "Metodologias de Teste",
        "Planejamento de Testes",
        "Relatórios de Testes",
        "TDD"
    ],
    "Turismo e Hospitalidade": [
        "Agente de Turismo",
        "Agente de Viagens",
        "Arrangeiro",
        "Atendente de Hotel",
        "Atendimento a Hóspedes",
        "Barman",
        "Bartender",
        "Bellboy",
        "Camareira",
        "Chefe de Recepção",
        "Condutor de Turismo",
        "Concierge",
        "Copeiro",
        "Garçom",
        "Governanta",
        "Guia de Turismo",
        "Hospitalidade",
        "Hospitality Management",
        "Hospedagem",
        "Hotelaria",
        "Maitre",
        "Motoboy",
        "Organização de Eventos",
        "Recepcionista de Hotel",
        "Recreacionista",
        "Reservas",
        "Serviços de Quarto",
        "Turismo Cultural",
        "Turismo de Aventura",
        "Turismo de Negócios",
        "Turismo Ecológico",
        "Turismo Rural"
    ]
} as const;

